- name: Create user `ewout`
  become: yes
  ansible.builtin.user:
    name: ewout
    password: $6$kunbsrRoein6bA8w$v37Lv35f9MxEtF09G3Q0MeqUN2Hvkt3IJz7OQhFwbSzvcqJHRXxBmLEjeiNNhpv5o8PBAkuWEV4xDOuNe02.Z1
    update_password: on_create
    append: yes
    groups:
      - wheel
    shell: /usr/bin/zsh
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_default
    comment: Ewout
