- name: Install basic GNOME Desktop
  become: yes
  community.general.pacman:
    name:
      - gdm
      - gnome-backgrounds
      - gnome-control-center
      - gnome-keyring
      - gnome-online-accounts

- name: Enable GDM
  become: yes
  ansible.builtin.systemd:
    name: gdm.service
    enabled: yes
