- name: Enable `multilib` repository for pacman
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  register: pacman-multilib-enable

- name: Refresh package index
  become: yes
  when: pacman-multilib-enable.changed
  community.general.pacman:
    update_cache: yes
