- name: Install cockpit and modules
  community.general.pacman:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-podman
      - cockpit-pcp

- name: Install PCP monitor
  community.general.pacman:
    name: pcp

- name: Enable PCP monitor service
  systemd:
    name: pmcd.service
    enabled: yes
    state: started

- name: Enable cockpit socket
  systemd:
    name: cockpit.socket
    enabled: yes
    state: started
