# Install general system utilities

- name: Install man command
  community.general.pacman:
    name: 
      - man-db
      - man-pages

- name: Install info
  community.general.pacman:
    name: texinfo

- name: Install git
  community.general.pacman:
    name: git

- name: Install sudo
  community.general.pacman:
    name: sudo

- name: Install vim
  community.general.pacman:
    name:
      - vim
      - vim-ansible
      - vim-editorconfig

# TODO: Install vim config as skeleton files

- name: Install screen
  community.general.pacman:
    name: screen

- name: Install tmux
  community.general.pacman:
    name: tmux

- name: Install zsh and optional packages
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-theme-powerlevel10k

# TODO: Install zsh/oh-my-zsh/powerlevel10k/... config as skeleton files

- name: Install Flatpak
  community.general.pacman:
    name: flatpak

- name: Install podman
  community.general.pacman:
    name:
      - podman
      - podman-compose
      - podman-dnsname

- name: Install python
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-virtualenv
